# Generated by Django 3.2.4 on 2021-06-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('STRIP', 'STRIP'), ('COD', 'COD')], max_length=100, null=True),
        ),
    ]
